### PR TITLE
feat: internationalization optimization

### PR DESCRIPTION
**Pull request by litikky**
## What this PR does / why we need it:
Internationalization optimization

## I have checked the following points:
- [x] I18n is finished and updated by cli
- [x] Form fields validation is added and length is limited
- [x] Display normally on small screen
- [x] Display normally when some data is empty or null
- [x] Display normally in english mode

## Which issue(s) this PR fixes:
Fixes #

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=299494&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwic3RhdGVzIjpbNDQwMiw3MTA0LDcxMDUsNDQwMyw0NDA0LDcxMDYsNDQwNiw0NDA3LDQ0MTIsNDUzOCw0NDEzLDQ0MTQsNDQxNSw0NDE2XSwiYXNzaWduZWVJRHMiOlsiMTAwMzE0NiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1164&type=TASK)

## Does this PR introduce a user interface change?

❎ No

## ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |       Internationalization document modified some English translations       |
| 🇨🇳 中文    |      国际化文档修改部分英文翻译        |

## Need cherry-pick to release versions?
❎ No

### CODE REVIEW

**Comment by litikky** [comment]
由于i18n英文修改，导致部分单测不通过，后续再修改

**Comment by McDaddy** [comment]
> 由于i18n英文修改，导致部分单测不通过，后续再修改

will merge after release of Apr 7

**Comment by litikky** [comment]
fix test

**Review by McDaddy — DISMISSED** [review]

**Pull request closed without merging**
