### PR TITLE
Hotfix: Fixed app list paging issues

### PR DESCRIPTION
**Pull request by sherotree**
## What type of PR is this?

- [ ] Feature
- [x] Bugfix
- [ ] Test
- [ ] Documentation
- [ ] Refactor
- [ ] Style
- [ ] Chore

## What this PR does / why we need it:
fix that turn the page of application list

## Which issue(s) this PR fixes:

Fixes #
it's 'list' instead of  'combineList' to map when it is pagination mode.

## Does this PR introduce a user interface change?

- [ ] Yes(screenshot is required)
- [ ] No

### CODE REVIEW

**Comment by McDaddy** [comment]
PR title is confusion..

**Review by daskyrk — APPROVED** [review]

**Pull request merged**
