### PR TITLE
feat:(components): introduce component lib

### PR DESCRIPTION
**Pull request by McDaddy**
## What this PR does / why we need it:
1. migrate components lib to erda-ui
2. remove lerna and use pnpm workspce instead
3. move common pkg to root, in order to reduce bundle size and easy version control
4. adjust cli scripts acrroding to the change above

## I have checked the following points:
- [x] I18n is finished and updated by cli
- [x] Form fields validation is added and length is limited
- [x] Display normally on small screen
- [x] Display normally when some data is empty or null
- [x] Display normally in english mode

## Which issue(s) this PR fixes:
Fixes #

- Fixes #your-issue_number
- [Erda Cloud Issue Link](paste your link here)

## Does this PR introduce a user interface change?

❎ No

## ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |    migrate @erda-ui/components          |
| 🇨🇳 中文    |  迁移入@erda-ui/components            |

## Need cherry-pick to release versions?
❎ No

### CODE REVIEW

**Comment by daskyrk** [comment]
conflict

**Comment by McDaddy** [comment]
> conflict

resolved

**Pull request merged**
