### PR TITLE
fix: deploy create releaseId select style bug

### PR DESCRIPTION
**Pull request by hujiahao-hjh**
## What this PR does / why we need it:
fix deploy create releaseId select style bug.

## Does this PR introduce a user interface change?

✅ Yes(screenshot is required)
image
->
image

## ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English | Fixed the width bug of the deploy center artifact ID select. |
| 🇨🇳 中文    | 修复了部署中心创建时制品id选择框下拉的宽度bug。 |

## Which versions should be patched?
release/1.2

## Which issue(s) this PR fixes:

Fixes # deploy create releaseId select style bug.

### CODE REVIEW

**Review by daskyrk — APPROVED** [review]

**Comment by daskyrk** [comment]
add changeLog

**Comment by laojun** [comment]
cherry-pick release/1.2

**Pull request merged**
