### PR TITLE
Refactor/add check build status cli

### PR DESCRIPTION
**Pull request by McDaddy**
## What this PR does / why we need it:
remove comparison-build script, because we can consolidate all build status in the pre-install step
So that I create check-build-status script to implement the same logic in pre-install step then we can take advantage of `if` condition function of pipeline. By this pipeline feature, we can skip build directly, no need to ask for build resource and queue

image

## Does this PR introduce a user interface change?

❎ No

## ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |              |
| 🇨🇳 中文    |              |

## Does this PR need be patched to older version?
❎ No

## Which issue(s) this PR fixes:

Fixes #

### CODE REVIEW

**Comment by daskyrk** [comment]
Nice

**Comment by daskyrk** [comment]
Conflict

**Comment by McDaddy** [comment]
> Conflict

resolved

**Pull request merged**
